#!/bin/tcsh

#SBATCH --job-name="train_isotonic_regression"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=30:00:00
#SBATCH --array=1-4
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=train_isotonic_regression_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/experiment08_dropout_all_storm_types/further_training"

set FIRST_LAYER_FILTER_COUNTS=("04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16" "04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16" "04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16" "04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16")
set DENSE_DROPOUT_RATES=("0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500")
set BATCHES_PER_EPOCH_COUNTS=("36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60")
set BATCHES_PER_UPDATE_COUNTS=("2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3")

set BEST_MODEL_INDICES=(8 55 63 70)
set j=${BEST_MODEL_INDICES[$SLURM_ARRAY_TASK_ID]}

set num_first_layer_filters=${FIRST_LAYER_FILTER_COUNTS[$j]}
set dense_dropout_rate=${DENSE_DROPOUT_RATES[$j]}
set num_batches_per_epoch=${BATCHES_PER_EPOCH_COUNTS[$j]}
set num_batches_per_update=${BATCHES_PER_UPDATE_COUNTS[$j]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/num-first-layer-filters=${num_first_layer_filters}_dense-dropout-rate=${dense_dropout_rate}_num-batches-per-epoch=${num_batches_per_epoch}_num-batches-per-update=${num_batches_per_update}"
echo $model_dir_name

python3 -u "${CODE_DIR_NAME}/train_scalar_iso_regression.py" \
--input_prediction_file_pattern="${model_dir_name}/isotonic_regression/training/predictions*.nc" \
--output_model_dir_name="${model_dir_name}/isotonic_regression"
