#!/bin/tcsh

#SBATCH --job-name="simplify_validation_files"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpu"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --array=1-94
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=simplify_validation_files_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set INPUT_DIR_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/shuffled_8hour_chunks/validation"
set OUTPUT_DIR_NAME="${INPUT_DIR_NAME}/800x800_grids"

set FILE_NUMBER_SET_STRINGS=("0 1" "2 3" "4 5" "6 7" "8 9" "10 11" "12 13" "14 15" "16 17" "18 19" "20 21" "22 23" "24 25" "26 27" "28 29" "30 31" "32 33" "34 35" "36 37" "38 39" "40 41" "42 43" "44 45" "46 47" "48 49" "50 51" "52 53" "54 55" "56 57" "58 59" "60 61" "62 63" "64 65" "66 67" "68 69" "70 71" "72 73" "74 75" "76 77" "78 79" "80 81" "82 83" "84 85" "86 87" "88 89" "90 91" "92 93" "94 95" "96 97" "98 99" "100 101" "102 103" "104 105" "106 107" "108 109" "110 111" "112 113" "114 115" "116 117" "118 119" "120 121" "122 123" "124 125" "126 127" "128 129" "130 131" "132 133" "134 135" "136 137" "138 139" "140 141" "142 143" "144 145" "146 147" "148 149" "150 151" "152 153" "154 155" "156 157" "158 159" "160 161" "162 163" "164 165" "166 167" "168 169" "170 171" "172 173" "174 175" "176 177" "178 179" "180 181" "182 183" "184 185" "186")

set file_number_set_string="${FILE_NUMBER_SET_STRINGS[$SLURM_ARRAY_TASK_ID]}"
set file_numbers=($file_number_set_string:as/ / /)

foreach file_number ($file_numbers)
    python3 -u "${CODE_DIR_NAME}/simplify_satellite_files.py" \
    --input_dir_name="${INPUT_DIR_NAME}" \
    --shuffled_file_number=${file_number} \
    --wavelengths_to_keep_microns 3.9 6.185 6.95 7.34 8.5 9.61 10.35 11.2 12.3 13.3 \
    --num_grid_rows_to_keep=800 \
    --num_grid_columns_to_keep=800 \
    --output_dir_name="${OUTPUT_DIR_NAME}"
end
