#!/bin/tcsh

#SBATCH --job-name="apply_neural_nets"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=04:00:00
#SBATCH --array=1-67
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/experiment10_xy_size_channels/further_training"
set EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_params_from_2017-2020_and_2022/simplified_all_wavelengths"

set GRID_ROW_COUNTS=("300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590")
set LAG_TIME_COUNTS=("3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7")
set FIRST_LAYER_FILTER_COUNTS=("10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40" "10" "20" "30" "40")

set BEST_MODEL_INDICES=(1 2 5 17 18 21 33 49 65)

set CYCLONE_ID_STRINGS=("2021AL01" "2021AL02" "2021AL03" "2021AL04" "2021AL05" "2021AL06" "2021AL07" "2021AL08" "2021AL09" "2021AL10" "2021AL11" "2021AL12" "2021AL13" "2021AL14" "2021AL15" "2021AL16" "2021AL17" "2021AL18" "2021AL19" "2021EP01" "2021EP02" "2021EP03" "2021EP04" "2021EP05" "2021EP06" "2021EP07" "2021EP08" "2021EP09" "2021EP10" "2021EP11" "2021EP12" "2021EP13" "2021EP14" "2021EP15" "2021EP16" "2021EP17" "2021EP18" "2021EP19" "2021WP01" "2021WP02" "2021WP03" "2021WP04" "2021WP05" "2021WP06" "2021WP07" "2021WP08" "2021WP09" "2021WP10" "2021WP11" "2021WP12" "2021WP13" "2021WP14" "2021WP15" "2021WP16" "2021WP17" "2021WP18" "2021WP19" "2021WP20" "2021WP21" "2021WP22" "2021WP23" "2021WP24" "2021WP25" "2021WP26" "2021WP27" "2021WP28" "2021WP29")

set i=$SLURM_ARRAY_TASK_ID

while ($i <= `expr $SLURM_ARRAY_TASK_ID` && $i <= $#CYCLONE_ID_STRINGS)
    set j=1
    
    while ($j <= ${#BEST_MODEL_INDICES})
        set model_index=${BEST_MODEL_INDICES[$j]}
        
        set num_grid_rows=${GRID_ROW_COUNTS[$model_index]}
        set num_lag_times=${LAG_TIME_COUNTS[$model_index]}
        set num_first_layer_filters=${FIRST_LAYER_FILTER_COUNTS[$model_index]}
        
        set model_dir_name="${TOP_MODEL_DIR_NAME}/num-grid-rows=${num_grid_rows}_num-lag-times=${num_lag_times}_num-first-layer-filters=${num_first_layer_filters}"
        echo $model_dir_name
        
        python3 -u "${CODE_DIR_NAME}/apply_neural_net.py" \
        --input_model_file_name="${model_dir_name}/model.h5" \
        --input_satellite_dir_name="${EXAMPLE_DIR_NAME}" \
        --cyclone_id_string="${CYCLONE_ID_STRINGS[$i]}" \
        --num_bnn_iterations=1 \
        --max_ensemble_size=100 \
        --data_aug_num_translations=8 \
        --output_dir_name="${model_dir_name}/validation"
    
        @ j = $j + 1
    end

    @ i = $i + 1
end
