#!/bin/tcsh

#SBATCH --job-name="train_neural_net"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=train_neural_net_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set TEMPLATE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/test_with_scalar_predictors/templates"
set TOP_OUTPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/test_with_scalar_predictors"

set TRAINING_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_project/learning_examples/rotated_with_storm_motion/imputed/normalized"
set VALIDATION_DIR_NAME="${TRAINING_DIR_NAME}"
set A_DECK_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/a_decks/processed_a_decks_2017-2022_norm_params_2017-2020.nc"

set template_file_name="${TEMPLATE_DIR_NAME}/model.h5"
set output_dir_name="${TOP_OUTPUT_DIR_NAME}"
echo $output_dir_name

python3 -u "${CODE_DIR_NAME}/train_neural_net_cira_ir.py" \
--input_template_file_name="${template_file_name}" \
--output_model_dir_name="${output_dir_name}" \
--lag_times_minutes 0 60 120 180 240 \
--num_examples_per_batch=21 \
--max_examples_per_cyclone=3 \
--num_rows_low_res=290 \
--num_columns_low_res=450 \
--data_aug_num_translations=3 \
--data_aug_mean_translation_low_res_px=12 \
--data_aug_stdev_translation_low_res_px=6 \
--synoptic_times_only=0 \
--scalar_a_deck_field_names "absolute_latitude_deg_n" "longitude_cosine" "longitude_sine" "eastward_motion_m_s01" "northward_motion_m_s01" "intensity_m_s01" "sea_level_pressure_pa" \
--a_deck_file_name="${A_DECK_FILE_NAME}" \
--satellite_dir_name_for_training="${TRAINING_DIR_NAME}" \
--training_years 2017 2018 \
--satellite_dir_name_for_validation="${VALIDATION_DIR_NAME}" \
--validation_years 2019 \
--num_epochs=1000 \
--num_training_batches_per_epoch=24 \
--num_validation_batches_per_epoch=12
