#!/bin/tcsh

#SBATCH --job-name="run_discard_test"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpu"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=01:00:00
#SBATCH --array=2,12,19,29,44,50,61,69
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=run_discard_test_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/experiment11_xy_size_channels"

set GRID_ROW_COUNTS=("300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300-pool-by-2" "300" "300" "300" "300" "400" "400" "400" "400" "500" "500" "500" "500" "590" "590" "590" "590")
set LAG_TIME_COUNTS=("3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "4" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "5" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "6" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7" "7")
set FIRST_LAYER_FILTER_COUNTS=("10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25" "10" "15" "20" "25")

set num_grid_rows=${GRID_ROW_COUNTS[$SLURM_ARRAY_TASK_ID]}
set num_lag_times=${LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
set num_first_layer_filters=${FIRST_LAYER_FILTER_COUNTS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/num-grid-rows=${num_grid_rows}_num-lag-times=${num_lag_times}_num-first-layer-filters=${num_first_layer_filters}"
echo $model_dir_name

python3 -u "${CODE_DIR_NAME}/run_discard_test.py" \
--input_prediction_file_pattern="${model_dir_name}/isotonic_regression/validation/predictions*.nc" \
--discard_fractions 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 \
--output_file_name="${model_dir_name}/isotonic_regression/validation/discard_test.nc"
