#!/bin/bash

#SBATCH --job-name="apply_neural_nets_testing_step1_case_studies"
#SBATCH --partition="bigmem"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=08:00:00
#SBATCH --array=0-4
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_testing_step1_case_studies_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_experiment05_domain_video_distribution"
EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/900x900_grids/testing"
A_DECK_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/a_decks/processed/a_decks_normalized.nc"

CYCLONE_ID_STRINGS=("2021AL06" "2021AL15" "2021WP01" "2021WP19" "2022EP15")

GRID_ROW_COUNTS=("600")
UNIFORM_DIST_FLAGS=("0")
LAG_TIME_COUNTS=("09")

i=$SLURM_ARRAY_TASK_ID

while [ $i -le $(( $SLURM_ARRAY_TASK_ID + 0 )) ] && [ $i -lt ${#CYCLONE_ID_STRINGS[@]} ]; do
    j=0
    
    while [ $j -lt ${#GRID_ROW_COUNTS[@]} ]; do
        num_grid_rows=${GRID_ROW_COUNTS[$j]}
        use_uniform_dist=${UNIFORM_DIST_FLAGS[$j]}
        num_lag_times=${LAG_TIME_COUNTS[$j]}

        model_dir_name="${TOP_MODEL_DIR_NAME}/num-grid-rows=${num_grid_rows}_use-uniform-dist=${use_uniform_dist}_num-lag-times=${num_lag_times}"
        echo $model_dir_name

        python3 -u "${CODE_DIR_NAME}/apply_neural_net_step1_preprocessing.py" \
        --input_model_file_name="${model_dir_name}/model.weights.h5" \
        --input_satellite_dir_name="${EXAMPLE_DIR_NAME}" \
        --input_a_deck_file_name="${A_DECK_FILE_NAME}" \
        --cyclone_id_string="${CYCLONE_ID_STRINGS[$i]}" \
        --data_aug_num_translations=8 \
        --data_aug_uniform_dist_flag=0 \
        --synoptic_times_only=0 \
        --output_dir_name="/scratch2/STI/mdl-sti/Ryan.Lagerquist/ml4tccf_models/paper_experiment05_domain_video_distribution/preprocessed_examples_gaussian_dist_num-lag-times=${num_lag_times}/case_studies"
        
        j=$(( $j + 1 ))
    done
    
    i=$(( $i + 1 ))
done
