#!/bin/bash

#SBATCH --job-name="create_multimodel_ensemble_testing_case_studies"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=08:00:00
#SBATCH --array=0-4
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=create_multimodel_ensemble_testing_case_studies_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_experiment05_domain_video_distribution/ensemble"

CYCLONE_ID_STRINGS=("2021AL06" "2021AL15" "2021WP01" "2021WP19" "2022EP15")

WAVELENGTH_GROUP_STRINGS_MICRONS=("8.500-9.610-12.300" "3.900-7.340-13.300" "6.950-10.350-11.200")

input_file_names_string=""
j=0

while [ $j -lt ${#WAVELENGTH_GROUP_STRINGS_MICRONS[@]} ]; do
    wavelength_group_string_microns=${WAVELENGTH_GROUP_STRINGS_MICRONS[$j]}
    input_file_names_string="${input_file_names_string} ${TOP_MODEL_DIR_NAME}/wavelengths-microns=${wavelength_group_string_microns}/isotonic_regression_gaussian_dist/uncertainty_calibration/testing/case_studies/predictions_${CYCLONE_ID_STRINGS[$SLURM_ARRAY_TASK_ID]}.nc"
    
    j=$(( $j + 1 ))
done

python3 -u "${CODE_DIR_NAME}/create_multimodel_ensemble.py" \
--input_prediction_file_names ${input_file_names_string} \
--max_total_ensemble_size=1000 \
--output_prediction_file_name="${TOP_MODEL_DIR_NAME}/3member_ensemble/isotonic_regression_gaussian_dist/uncertainty_calibration/testing/case_studies/predictions_${CYCLONE_ID_STRINGS[$SLURM_ARRAY_TASK_ID]}.nc"
