#!/bin/tcsh

#SBATCH --job-name="shuffle_satellite_files_validation"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpu"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=shuffle_satellite_files_validation_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set INPUT_DIR_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper"
set OUTPUT_DIR_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/shuffled_8hour_chunks_500by500/validation"

python3 -u "${CODE_DIR_NAME}/shuffle_satellite_files.py" \
--input_satellite_dir_name="${INPUT_DIR_NAME}" \
--num_chunks_per_input_file=3 \
--num_chunks_per_output_file=8 \
--output_time_interval_minutes=30 \
--cyclone_id_strings "2020AL01" "2020AL02" "2020AL03" "2020AL04" "2020AL05" "2020AL06" "2020AL07" "2020AL08" "2020AL09" "2020AL10" "2020AL11" "2020AL12" "2020AL13" "2020AL14" "2020AL15" "2020AL16" "2020AL17" "2020AL18" "2020AL19" "2020AL20" "2020AL21" "2020AL22" "2020AL23" "2020AL24" "2020AL25" "2020AL26" "2020AL27" "2020AL28" "2020AL29" "2020AL30" "2020AL31" "2020WP01" "2020WP02" "2020WP03" "2020WP04" "2020WP05" "2020WP06" "2020WP07" "2020WP08" "2020WP09" "2020WP10" "2020WP11" "2020WP12" "2020WP13" "2020WP14" "2020WP15" "2020WP16" "2020WP17" "2020WP18" "2020WP19" "2020WP20" "2020WP21" "2020WP22" "2020WP23" "2020WP24" "2020WP25" "2020WP26" "2021EP01" "2021EP02" "2021EP03" "2021EP04" "2021EP05" "2021EP06" "2021EP07" "2021EP08" "2021EP09" "2021EP10" "2021EP11" "2021EP12" "2021EP13" "2021EP14" "2021EP15" "2021EP16" "2021EP17" "2021EP18" "2021EP19" \
--first_output_file_num=0 \
--output_satellite_dir_name="${OUTPUT_DIR_NAME}"
