#!/bin/bash

#SBATCH --job-name="simplify_testing_files"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=04:00:00
#SBATCH --array=0-66
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=simplify_testing_files_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python3`

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
INPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper"
OUTPUT_DIR_NAME="${INPUT_DIR_NAME}/900x900_grids/testing"

CYCLONE_ID_STRINGS=("2021AL02" "2021AL03" "2021AL01" "2021AL11" "2021AL15" "2021AL16" "2021WP18" "2022EP14" "2021AL08" "2021WP29" "2022EP04" "2022EP03" "2022EP02" "2022EP18" "2021AL18" "2021WP23" "2021AL19" "2021AL12" "2022EP15" "2021AL13" "2021WP12" "2021WP04" "2021WP26" "2021WP06" "2021AL04" "2022EP01" "2021WP05" "2021WP08" "2022EP09" "2021WP10" "2021WP15" "2021WP03" "2021WP28" "2021WP20" "2021WP17" "2022EP10" "2022EP08" "2021WP14" "2021WP21" "2022EP12" "2021WP07" "2022EP17" "2021WP11" "2022EP06" "2022EP11" "2021AL10" "2021AL07" "2021WP24" "2022EP19" "2021WP22" "2021AL14" "2021WP25" "2021WP02" "2021WP16" "2022EP13" "2021WP19" "2021AL05" "2021WP09" "2021AL17" "2022EP07" "2021WP01" "2021AL09" "2021WP13" "2022EP05" "2021WP27" "2021AL06" "2022EP16")

python3 -u "${CODE_DIR_NAME}/simplify_satellite_files.py" \
--input_dir_name="${INPUT_DIR_NAME}" \
--cyclone_id_string="${CYCLONE_ID_STRINGS[$SLURM_ARRAY_TASK_ID]}" \
--wavelengths_to_keep_microns 3.9 6.185 6.95 7.34 8.5 9.61 10.35 11.2 12.3 13.3 \
--num_grid_rows_to_keep=900 \
--num_grid_columns_to_keep=900 \
--output_dir_name="${OUTPUT_DIR_NAME}"
