#!/bin/bash

#SBATCH --job-name="apply_neural_nets_testing_case_studies"
#SBATCH --partition="bigmem"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=04:00:00
#SBATCH --array=0-39
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_testing_case_studies_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_experiment05_domain_video_distribution/ensemble"
EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/900x900_grids/testing"
A_DECK_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/a_decks/processed/a_decks_normalized.nc"

CYCLONE_ID_STRINGS=("2021AL06" "2021AL06" "2021AL06" "2021AL06" "2021AL06" "2021AL06" "2021AL06" "2021AL06" "2021AL06" "2021AL06" "2021AL06"    "2021AL15" "2021AL15" "2021AL15" "2021AL15" "2021AL15" "2021AL15" "2021AL15" "2021AL15"      "2021WP01" "2021WP01" "2021WP01" "2021WP01" "2021WP01" "2021WP01"       "2021WP19" "2021WP19" "2021WP19" "2021WP19" "2021WP19" "2021WP19"     "2022EP15" "2022EP15" "2022EP15" "2022EP15" "2022EP15" "2022EP15" "2022EP15" "2022EP15" "2022EP15")
VALID_DATE_STRINGS=("20210809" "20210810" "20210811" "20210812" "20210813" "20210814" "20210815" "20210816" "20210817" "20210818" "20210820"    "20210916" "20210917" "20210918" "20210919" "20210921" "20210922" "20210923" "20210924"      "20210217" "20210218" "20210219" "20210220" "20210221" "20210222"       "20210906" "20210907" "20210908" "20210909" "20210910" "20210911"     "20220921" "20220922" "20220923" "20220924" "20220925" "20220926" "20220927" "20220928" "20220929")

WAVELENGTH_GROUP_STRINGS_MICRONS=("8.500-9.610-12.300" "3.900-7.340-13.300" "3.900-6.185-6.950" "6.950-10.350-11.200")

i=$SLURM_ARRAY_TASK_ID

while [ $i -le $(( $SLURM_ARRAY_TASK_ID + 0 )) ] && [ $i -lt ${#CYCLONE_ID_STRINGS[@]} ]; do
    j=0
    
    while [ $j -lt ${#WAVELENGTH_GROUP_STRINGS_MICRONS[@]} ]; do
        wavelength_group_string_microns=${WAVELENGTH_GROUP_STRINGS_MICRONS[$j]}
        model_dir_name="${TOP_MODEL_DIR_NAME}/wavelengths-microns=${wavelength_group_string_microns}"
        echo $model_dir_name

        python3 -u "${CODE_DIR_NAME}/apply_neural_net.py" \
        --input_model_file_name="${model_dir_name}/model.weights.h5" \
        --input_satellite_dir_name="${EXAMPLE_DIR_NAME}" \
        --input_a_deck_file_name="${A_DECK_FILE_NAME}" \
        --cyclone_id_string="${CYCLONE_ID_STRINGS[$i]}" \
        --valid_date_string="${VALID_DATE_STRINGS[$i]}" \
        --data_aug_num_translations=8 \
        --data_aug_uniform_dist_flag=0 \
        --random_seed=6695 \
        --synoptic_times_only=0 \
        --output_file_name="${model_dir_name}/testing_gaussian_dist/case_studies/predictions_${CYCLONE_ID_STRINGS[$i]}_${VALID_DATE_STRINGS[$i]}.nc"
        
        j=$(( $j + 1 ))
    done
    
    i=$(( $i + 1 ))
done
