#!/bin/tcsh

#SBATCH --job-name="simplify_validation_files"
#SBATCH --partition="bigmem"
#SBATCH --account="gsd-hpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=08:00:00
#SBATCH --array=1-29
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=simplify_validation_files_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set INPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/parallax_corrected/normalized_params_from_2017-2020_and_2022"
set OUTPUT_DIR_NAME="${INPUT_DIR_NAME}/simplified_all_wavelengths"

set CYCLONE_ID_STRINGS=("2021WP01" "2021WP02" "2021WP03" "2021WP04" "2021WP05" "2021WP06" "2021WP07" "2021WP08" "2021WP09" "2021WP10" "2021WP11" "2021WP12" "2021WP13" "2021WP14" "2021WP15" "2021WP16" "2021WP17" "2021WP18" "2021WP19" "2021WP20" "2021WP21" "2021WP22" "2021WP23" "2021WP24" "2021WP25" "2021WP26" "2021WP27" "2021WP28" "2021WP29")

set cyclone_id_string="${CYCLONE_ID_STRINGS[$SLURM_ARRAY_TASK_ID]}"

python3 -u "${CODE_DIR_NAME}/simplify_satellite_files.py" \
--input_dir_name="${INPUT_DIR_NAME}" \
--cyclone_id_string="${cyclone_id_string}" \
--wavelengths_to_keep_microns 3.9 6.185 6.95 7.34 8.5 9.61 10.35 11.2 12.3 13.3 \
--output_dir_name="${OUTPUT_DIR_NAME}"
