#!/bin/bash

#SBATCH --job-name="waf2024_plot_full_track"
#SBATCH --partition="bigmem"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=00:10:00
#SBATCH --array=0-4
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=waf2024_plot_full_track_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
EBTRK_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/extended_best_track_thru_nov2023.nc"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_experiment05_domain_video_distribution/ensemble"

model_dir_name="${TOP_MODEL_DIR_NAME}/3member_ensemble"
echo $model_dir_name

CYCLONE_ID_STRINGS=("2021AL06" "2021AL15" "2021WP01" "2021WP19" "2022EP15")

python3 -u "${CODE_DIR_NAME}/waf2024_plot_full_track.py" \
--input_ascii_prediction_dir_name="${model_dir_name}/isotonic_regression_gaussian_dist/uncertainty_calibration/testing/case_studies/predictions_${CYCLONE_ID_STRINGS[$SLURM_ARRAY_TASK_ID]}" \
--input_ebtrk_file_name="${EBTRK_FILE_NAME}" \
--cyclone_id_string="${CYCLONE_ID_STRINGS[$SLURM_ARRAY_TASK_ID]}" \
--output_file_name="${model_dir_name}/isotonic_regression_gaussian_dist/uncertainty_calibration/testing/case_studies/predictions_${CYCLONE_ID_STRINGS[$SLURM_ARRAY_TASK_ID]}/full_track.jpg"
