#!/bin/bash

#SBATCH --job-name="train_neural_nets_unshuffled_test"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=18:00:00
#SBATCH --array=3,6,10,13,17,20,24,27,31,34,38,41,45,48,52,55
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=train_neural_nets_unshuffled_test_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
TEMPLATE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_experiment02_with_short_track/templates"
TOP_OUTPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_experiment02_with_short_track/unshuffled_test"

TRAINING_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/900x900_grids/training"
VALIDATION_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/900x900_grids/validation"
A_DECK_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/a_decks/processed/a_decks_normalized.nc"
SHORT_TRACK_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/short_track_data/processed"

GRID_ROW_COUNTS=("300" "300" "300" "300" "300" "300" "300" "400" "400" "400" "400" "400" "400" "400" "500" "500" "500" "500" "500" "500" "500" "600" "600" "600" "600" "600" "600" "600" "300" "300" "300" "300" "300" "300" "300" "400" "400" "400" "400" "400" "400" "400" "500" "500" "500" "500" "500" "500" "500" "600" "600" "600" "600" "600" "600" "600")
MAIN_POOLING_FACTORS=("2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3")
LAG_TIME_COUNTS=("1" "2" "3" "4" "5" "6" "7" "1" "2" "3" "4" "5" "6" "7" "1" "2" "3" "4" "5" "6" "7" "1" "2" "3" "4" "5" "6" "7" "1" "2" "3" "4" "5" "6" "7" "1" "2" "3" "4" "5" "6" "7" "1" "2" "3" "4" "5" "6" "7" "1" "2" "3" "4" "5" "6" "7")

num_grid_rows=${GRID_ROW_COUNTS[$SLURM_ARRAY_TASK_ID]}
main_pooling_factor=${MAIN_POOLING_FACTORS[$SLURM_ARRAY_TASK_ID]}
num_lag_times=${LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}

template_file_name="${TEMPLATE_DIR_NAME}/num-grid-rows=${num_grid_rows}_main-pooling-factor=${main_pooling_factor}_num-lag-times=${num_lag_times}/model.keras"
output_dir_name="${TOP_OUTPUT_DIR_NAME}/num-grid-rows=${num_grid_rows}_main-pooling-factor=${main_pooling_factor}_num-lag-times=${num_lag_times}"
echo $output_dir_name

POSSIBLE_LAG_TIMES_MINUTES=("0" "30" "60" "90" "120" "150" "180")
lag_time_string_minutes=""
i=0

while [ "$i" -lt "$num_lag_times" ]; do
    lag_time_string_minutes+=" ${POSSIBLE_LAG_TIMES_MINUTES[$i]}"
    ((i++))
done

echo $lag_time_string_minutes

# TODO(thunderhoser): Not sure about short_track_center_each_lag_diffly.

python3 -u "${CODE_DIR_NAME}/train_neural_net_simple.py" \
--input_template_file_name="${template_file_name}" \
--output_model_dir_name="${output_dir_name}" \
--lag_times_minutes ${lag_time_string_minutes} \
--low_res_wavelengths_microns 8.500 9.610 12.300 \
--num_examples_per_batch=20 \
--max_examples_per_cyclone=2 \
--num_rows_low_res=${num_grid_rows} \
--num_columns_low_res=${num_grid_rows} \
--input_short_track_dir_name="${SHORT_TRACK_DIR_NAME}" \
--short_track_max_lead_minutes=350 \
--short_track_center_each_lag_diffly=0 \
--data_aug_num_translations=1 \
--data_aug_mean_translation_low_res_px=10 \
--data_aug_stdev_translation_low_res_px=5 \
--data_aug_within_mean_trans_px=5 \
--data_aug_within_stdev_trans_px=2.5 \
--synoptic_times_only=0 \
--a_deck_file_name="${A_DECK_FILE_NAME}" \
--scalar_a_deck_field_names "absolute_latitude_deg_n" "longitude_cosine" "longitude_sine" "intensity_m_s01" "sea_level_pressure_pa" \
--remove_nontropical_systems=0 \
--use_shuffled_data=0 \
--satellite_dir_name_for_training="${TRAINING_DIR_NAME}" \
--training_years 2020 \
--satellite_dir_name_for_validation="${VALIDATION_DIR_NAME}" \
--validation_years 2020 \
--num_epochs=1000 \
--num_training_batches_per_epoch=36 \
--num_validation_batches_per_epoch=12 \
--plateau_patience_epochs=20 \
--plateau_learning_rate_multiplier=0.6 \
--early_stopping_patience_epochs=500
