#!/bin/tcsh

#SBATCH --job-name="create_dumb_ensemble"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=create_dumb_ensemble_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/experiment08_dropout_all_storm_types/further_training"
set OUTPUT_DIR_NAME="${TOP_MODEL_DIR_NAME}/dumb_ensemble"

set FIRST_LAYER_FILTER_COUNTS=("08" "12" "04" "08")
set DENSE_DROPOUT_RATES=("0.125" "0.375" "0.500" "0.500")
set BATCHES_PER_EPOCH_COUNTS=("48" "60" "48" "60")
set BATCHES_PER_UPDATE_COUNTS=("2" "3" "2" "3")

set CYCLONE_ID_STRINGS=("2022EP01" "2022EP02" "2022EP03" "2022EP04" "2022EP05" "2022EP06" "2022EP07" "2022EP08" "2022EP09" "2022EP10" "2022EP11" "2022EP12" "2022EP13" "2022EP14" "2022EP15" "2022EP16" "2022EP17" "2022EP18" "2022EP19")
set i=1

while ($i <= ${#CYCLONE_ID_STRINGS})
    set input_file_names_string=""
    set j=1
    
    while ($j <= ${#FIRST_LAYER_FILTER_COUNTS})
        set num_first_layer_filters=${FIRST_LAYER_FILTER_COUNTS[$j]}
        set dense_dropout_rate=${DENSE_DROPOUT_RATES[$j]}
        set num_batches_per_epoch=${BATCHES_PER_EPOCH_COUNTS[$j]}
        set num_batches_per_update=${BATCHES_PER_UPDATE_COUNTS[$j]}
        
        set input_file_names_string="${input_file_names_string} ${TOP_MODEL_DIR_NAME}/num-first-layer-filters=${num_first_layer_filters}_dense-dropout-rate=${dense_dropout_rate}_num-batches-per-epoch=${num_batches_per_epoch}_num-batches-per-update=${num_batches_per_update}/isotonic_regression/validation/with_random_seed/predictions_${CYCLONE_ID_STRINGS[$i]}.nc"
        @ j = $j + 1
    end
    
    python3 -u "${CODE_DIR_NAME}/create_multimodel_ensemble.py" \
    --input_prediction_file_names ${input_file_names_string} \
    --max_total_ensemble_size=200 \
    --output_prediction_file_name="${OUTPUT_DIR_NAME}/isotonic_regression/validation/predictions_${CYCLONE_ID_STRINGS[$i]}.nc"

    @ i = $i + 1
end
