#!/bin/bash

#SBATCH --job-name="evaluate_neural_nets"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=01:00:00
#SBATCH --array=0-24
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_neural_nets_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/intensity_experiment01"

SATELLITE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/800x800_grids"
A_DECK_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/a_decks/including_western_pacific_a-decks_not-b-decks/processed_a_decks_2016-2022_normalized_structure.nc"
TARGET_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/extended_best_track_thru_nov2023.nc"

GRAD_ACCUM_STEP_COUNTS=("01" "02" "03" "04" "05" "01" "02" "03" "04" "05" "01" "02" "03" "04" "05" "01" "02" "03" "04" "05" "01" "02" "03" "04" "05")
INIT_LEARNING_RATES=("0.0001" "0.0001" "0.0001" "0.0001" "0.0001" "0.0005" "0.0005" "0.0005" "0.0005" "0.0005" "0.0007" "0.0007" "0.0007" "0.0007" "0.0007" "0.0009" "0.0009" "0.0009" "0.0009" "0.0009" "0.0011" "0.0011" "0.0011" "0.0011" "0.0011")

num_grad_accum_steps=${GRAD_ACCUM_STEP_COUNTS[$SLURM_ARRAY_TASK_ID]}
init_learning_rate=${INIT_LEARNING_RATES[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/num-grad-accum-steps=${num_grad_accum_steps}_init-learning-rate=${init_learning_rate}"
echo $model_dir_name

python3 -u "${CODE_DIR_NAME}/evaluate_neural_net_for_structure.py" \
--input_prediction_file_pattern="${model_dir_name}/validation/predictions*.nc" \
--output_dir_name="${model_dir_name}/validation"
