#!/bin/bash

#SBATCH --job-name="apply_neural_nets_testing_step2_case_studies"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=08:00:00
#SBATCH --array=0-4
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_testing_step2_case_studies_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_experiment05_domain_video_distribution/ensemble"
EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/900x900_grids/testing"
A_DECK_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/a_decks/processed/a_decks_normalized.nc"

CYCLONE_ID_STRINGS=("2021AL06" "2021AL15" "2021WP01" "2021WP19" "2022EP15")

WAVELENGTH_GROUP_STRINGS_MICRONS=("8.500-9.610-12.300" "3.900-7.340-13.300" "3.900-6.185-6.950" "6.950-10.350-11.200")

i=$SLURM_ARRAY_TASK_ID

while [ $i -le $(( $SLURM_ARRAY_TASK_ID + 0 )) ] && [ $i -lt ${#CYCLONE_ID_STRINGS[@]} ]; do
    j=0
    
    while [ $j -lt ${#WAVELENGTH_GROUP_STRINGS_MICRONS[@]} ]; do
        wavelength_group_string_microns=${WAVELENGTH_GROUP_STRINGS_MICRONS[$j]}
        model_dir_name="${TOP_MODEL_DIR_NAME}/wavelengths-microns=${wavelength_group_string_microns}"
        echo $model_dir_name

        python3 -u "${CODE_DIR_NAME}/apply_neural_net_step2_inference.py" \
        --input_model_file_name="${model_dir_name}/model.weights.h5" \
        --input_example_dir_name="/scratch2/STI/mdl-sti/Ryan.Lagerquist/ml4tccf_models/paper_experiment05_domain_video_distribution/preprocessed_examples_gaussian_dist_all_wavelengths_num-lag-times=09/case_studies" \
        --cyclone_id_string="${CYCLONE_ID_STRINGS[$i]}" \
        --output_dir_name="${model_dir_name}/testing_gaussian_dist/case_studies"
        
        j=$(( $j + 1 ))
    done
    
    i=$(( $i + 1 ))
done
