#!/bin/tcsh

#SBATCH --job-name="apply_neural_nets"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=30:00:00
#SBATCH --array=1-80%70
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/experiment08_dropout_all_storm_types"
set VALIDATION_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_params_from_2017-2020/simplified_all_wavelengths"

set FIRST_LAYER_FILTER_COUNTS=("04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16" "04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16" "04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16" "04" "04" "04" "04" "04" "08" "08" "08" "08" "08" "12" "12" "12" "12" "12" "16" "16" "16" "16" "16")
set DENSE_DROPOUT_RATES=("0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.125" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.250" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.375" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500")
set BATCHES_PER_EPOCH_COUNTS=("36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60" "36" "36" "48" "48" "60")
set BATCHES_PER_UPDATE_COUNTS=("2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3" "2" "3" "2" "3" "3")

set num_first_layer_filters=${FIRST_LAYER_FILTER_COUNTS[$SLURM_ARRAY_TASK_ID]}
set dense_dropout_rate=${DENSE_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set num_batches_per_epoch=${BATCHES_PER_EPOCH_COUNTS[$SLURM_ARRAY_TASK_ID]}
set num_batches_per_update=${BATCHES_PER_UPDATE_COUNTS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/num-first-layer-filters=${num_first_layer_filters}_dense-dropout-rate=${dense_dropout_rate}_num-batches-per-epoch=${num_batches_per_epoch}_num-batches-per-update=${num_batches_per_update}"
echo $model_dir_name

set CYCLONE_ID_STRINGS=("2022EP01" "2022EP02" "2022EP03" "2022EP04" "2022EP05" "2022EP06" "2022EP07" "2022EP08" "2022EP09" "2022EP10" "2022EP11" "2022EP12" "2022EP13" "2022EP14" "2022EP15" "2022EP16" "2022EP17" "2022EP18" "2022EP19")
set i=1

while ($i <= ${#CYCLONE_ID_STRINGS})
    python3 -u "${CODE_DIR_NAME}/apply_neural_net.py" \
    --input_model_file_name="${model_dir_name}/model.h5" \
    --input_satellite_dir_name="${VALIDATION_DIR_NAME}" \
    --cyclone_id_string="${CYCLONE_ID_STRINGS[$i]}" \
    --num_bnn_iterations=1 \
    --max_ensemble_size=100 \
    --data_aug_num_translations=8 \
    --output_dir_name="${model_dir_name}/validation"

    @ i = $i + 1
end
