#!/bin/tcsh

#SBATCH --job-name="apply_neural_nets_2017AL01_1translation"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpu"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=06:00:00
#SBATCH --array=1
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_2017AL01_1translation_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_standalone/ml4tccf"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_models/paper_ensemble/tropical_only"
set EXAMPLE_DIR_NAME="/scratch2/BMC/gsd-hpcs/Ryan.Lagerquist/ml4tccf_project/satellite_data/processed/normalized_for_paper/simplified_all_wavelengths"

set CYCLONE_ID_STRINGS=("2017AL01")
set i=$SLURM_ARRAY_TASK_ID

set WAVELENGTH_GROUP_STRINGS_MICRONS=("6.950-10.350-11.200")

while ($i <= `expr $SLURM_ARRAY_TASK_ID + 2` && $i <= $#CYCLONE_ID_STRINGS)
    set cyclone_id_string="${CYCLONE_ID_STRINGS[$i]}"
    set j=1
    
    while ($j <= $#WAVELENGTH_GROUP_STRINGS_MICRONS)
        set wavelength_group_string_microns=${WAVELENGTH_GROUP_STRINGS_MICRONS[$j]}
        
        set model_dir_name="${TOP_MODEL_DIR_NAME}/wavelengths-microns=${wavelength_group_string_microns}"
        echo $model_dir_name
        
        python3 -u "${CODE_DIR_NAME}/apply_neural_net_2gpus.py" \
        --input_model_file_name="${model_dir_name}/model.h5" \
        --input_satellite_dir_name="${EXAMPLE_DIR_NAME}" \
        --cyclone_id_string="${cyclone_id_string}" \
        --num_bnn_iterations=1 \
        --max_ensemble_size=100 \
        --data_aug_num_translations=1 \
        --output_dir_name="${model_dir_name}/timing_tests/1translation"
        
        @ j = $j + 1
    end
    
    @ i = $i + 1
end
